Updated the git_hygiene check

diff --git a/.github/workflows/git_hygine.yml b/.github/workflows/git_hygine.yml
--- a/.github/workflows/git_hygine.yml
+++ b/.github/workflows/git_hygine.yml
@@ -15,4 +15,11 @@ jobs:
       - name: Check the branch name for PR ${{ github.event.pull_request.title }}
         shell: bash
         run: |
-          [[ "$BRANCH_NAME" =~ ^(enh|ref|fix|doc|msc)/([A-Za-z0-9]+(-[A-Za-z0-9]+)+)$ ]]
+          echo "Checking format of $BRANCH_NAME"
+          if [[ "$BRANCH_NAME" =~ ^(enh|ref|fix|doc|msc)/([A-Za-z0-9]+(-[A-Za-z0-9]+)+)$ ]]; then
+            echo "Passed"
+            exit 0
+          else
+            echo "Failed. Must use prefix of enh/ref/fix/doc/msc with a single slash and a name separated by hyphens"
+            exit 1
+          fi
